version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: XCPC_board_mysql
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=10086"
      - "MYSQL_DATABASE=XCPC_board_mysql"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
  redis:
    image: redis:7.0
    container_name: XCPC_board_redis
    restart: always
    command: redis-server --requirepass 10086
    volumes:
      - ./redis/datadir:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    ports:
      - 6379:6379